{
 "title": "Processos - Detailed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "process",
    "label": "Processos",
    "query": {
     "query": "label_values({instance=\"$instance\"},process)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "process" },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by() (memory_usage{instance=\"$instance\", process=\"$process\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by() (cpu_usage{instance=\"$instance\", process=\"$process\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "avg by() (virt_mem{instance=\"$instance\", process=\"$process\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "RES Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg by() (res_mem{instance=\"$instance\", process=\"$process\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by() (time{instance=\"$instance\", process=\"$process\"})",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}