{
 "title": "Processos - General",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "processes",
    "label": "Processos",
    "query": {
     "query": "label_values({instance=\"$instance\"},process)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(process) (topk(10, cpu_usage))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(process) (topk(10, memory_usage))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RES Memory",
   "type": "timeseries",
   "description": "the non-swapped physical memory that a process has used.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg by(process) (topk(10, res_mem))",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "description": "virtual memory size of the process.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(process) (topk(10, virt_mem))",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Tempo em execução",
   "type": "timeseries",
   "description": "the cumulated CPU time",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(process) (topk(10, time))",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}